import * as FaIcons from 'react-icons/fa';

export const availableIcons = [
    FaIcons.FaAtlas,
    FaIcons.FaAtom,
    FaIcons.FaBabyCarriage,
    FaIcons.FaBath,
    FaIcons.FaBed,
    FaIcons.FaBeer,
    FaIcons.FaBookReader,
    FaIcons.FaBusAlt,
    FaIcons.FaCar,
    FaIcons.FaCloudSun,
    FaIcons.FaDove,
    FaIcons.FaEnvelope,
    FaIcons.FaHeart,
    FaIcons.FaHiking,
    FaIcons.FaHome,
    FaIcons.FaHotjar,
    FaIcons.FaIcons,
    FaIcons.FaJsSquare,
    FaIcons.FaList,
    FaIcons.FaMapMarked,
    FaIcons.FaMortarPestle,
]
